import { Exercise, ExerciseCategory } from '../types';

export const EXERCISES: Exercise[] = [
  { id: 'ex_001', name: '노르딕 컬', category: '하체', equipment: '머신', description: '다이나믹' },
  { id: 'ex_002', name: '뉴트럴 그립 랫 풀 다운', category: '등', equipment: '머신', description: '다이나믹' },
  { id: 'ex_003', name: '뉴트럴 그립 풀 업', category: '등', equipment: '맨몸' },
  { id: 'ex_004', name: '데드리프트', category: '등', equipment: '바벨' },
  { id: 'ex_005', name: '딥스', category: '가슴', equipment: '맨몸' },
  { id: 'ex_006', name: '딥스 트라이셉스', category: '가슴', equipment: '머신', description: '다이나믹' },
  { id: 'ex_007', name: '랫 풀 다운', category: '등', equipment: '머신', description: '다이나믹' },
  { id: 'ex_008', name: '레그 레이즈', category: '하체', equipment: '머신' },
  { id: 'ex_009', name: '레그 프레스', category: '하체', equipment: '머신' },
  { id: 'ex_010', name: '레터럴 로우', category: '등', equipment: '머신', description: '소리넥스' },
  { id: 'ex_011', name: '레터럴 로우', category: '등', equipment: '머신' },
  { id: 'ex_012', name: '레터럴 로우 버티컬', category: '등', equipment: '머신', description: '소리넥스' },
  { id: 'ex_013', name: '레터럴 로우 버티컬', category: '등', equipment: '머신' },
  { id: 'ex_014', name: '로우', category: '등', equipment: '머신', description: '라이프피트니스' },
  { id: 'ex_015', name: '리어 델토이드', category: '어깨', equipment: '머신', description: '라이프피트니스' },
  { id: 'ex_016', name: '리어 델토이드', category: '어깨', equipment: '머신', description: '다이나믹' },
  { id: 'ex_017', name: '밀리터리 프레스', category: '어깨', equipment: '바벨' },
  { id: 'ex_018', name: '벤치프레스', category: '가슴', equipment: '바벨' },
  { id: 'ex_019', name: '벤치프레스', category: '가슴', equipment: '머신', description: '소리넥스' },
  { id: 'ex_020', name: '벤치프레스', category: '가슴', equipment: '머신', description: '아메리칸' },
  { id: 'ex_021', name: '벤트 오버 레터럴 레이즈', category: '어깨', equipment: '덤벨' },
  { id: 'ex_022', name: '브이 스쿼트', category: '하체', equipment: '머신', description: '아메리칸' },
  { id: 'ex_023', name: '사이드 레터럴 레이즈', category: '어깨', equipment: '머신' },
  { id: 'ex_024', name: '사이드 레터럴 레이즈 체인', category: '어깨', equipment: '머신' },
  { id: 'ex_025', name: '사이드 밴드', category: '복근', equipment: '덤벨' },
  { id: 'ex_026', name: '숄더 프레스', category: '어깨', equipment: '머신', description: '아메리칸' },
  { id: 'ex_027', name: '스쿼트', category: '하체', equipment: '바벨' },
  { id: 'ex_028', name: '암컬', category: '팔', equipment: '머신' },
  { id: 'ex_029', name: '앱도미널', category: '복근', equipment: '머신' },
  { id: 'ex_030', name: '언더 그립 랫 풀 다운', category: '등', equipment: '머신', description: '다이나믹' },
  { id: 'ex_031', name: '언더핸드 친 업', category: '등', equipment: '맨몸' },
  { id: 'ex_032', name: '와이드 그립 랫 풀 다운', category: '등', equipment: '머신', description: '다이나믹' },
  { id: 'ex_033', name: '와이드 그립 풀 업', category: '등', equipment: '맨몸' },
  { id: 'ex_034', name: '인클라인 프레스', category: '가슴', equipment: '머신', description: '아메리칸' },
  { id: 'ex_035', name: '인클라인 프레스', category: '가슴', equipment: '머신' },
  { id: 'ex_036', name: '케이블 암 풀 다운', category: '등', equipment: '케이블' },
  { id: 'ex_037', name: '케이블 프레스 다운', category: '팔', equipment: '케이블' },
  { id: 'ex_038', name: '토르소 로테이션', category: '복근', equipment: '머신', description: '라이프피트니스' },
  { id: 'ex_039', name: '팩토리얼 플라이', category: '가슴', equipment: '머신', description: '라이프피트니스' },
  { id: 'ex_040', name: '펙 덱 플라이', category: '가슴', equipment: '머신', description: '다이나믹' },
  { id: 'ex_041', name: '펙 덱 플라이', category: '가슴', equipment: '머신', description: '엠토쳐' },
  { id: 'ex_042', name: '풀 업', category: '등', equipment: '맨몸' },
  { id: 'ex_043', name: '해머 컬 머신', category: '팔', equipment: '머신', description: '다이나믹' },
  { id: 'ex_044', name: '핵스쿼트', category: '하체', equipment: '머신', description: '다이나믹' },
  { id: 'ex_045', name: '힙 쓰러스트', category: '하체', equipment: '머신' },
  { id: 'ex_046', name: '힙 어덕션', category: '하체', equipment: '머신', description: '라이프피트니스' },
  { id: 'ex_047', name: '힙 업덕션', category: '하체', equipment: '머신', description: '라이프피트니스' },
];

// 하위 호환: 기존 DEFAULT_EXERCISES 참조를 위한 alias
export const DEFAULT_EXERCISES = EXERCISES;

export const CATEGORY_LABELS: Record<ExerciseCategory, string> = {
  가슴: '가슴',
  등: '등',
  어깨: '어깨',
  팔: '팔',
  하체: '하체',
  복근: '복근',
};
