import { Exercise, ExerciseCategory } from '../types';

export const EXERCISES: Exercise[] = [
  { id: 'lg_001', name: '노르딕 컬', category: '하체', equipment: '머신', description: '다이나믹', alternativeExercises: ['lg_002'] },
  { id: 'bk_001', name: '뉴트럴 그립 랫 풀 다운', category: '등', equipment: '머신', description: '다이나믹', alternativeExercises: ['bk_002'] },
  { id: 'lg_002', name: '레그 컬', category: '하체', equipment: '머신', description: '다이나믹', alternativeExercises: ['lg_001'] },
  { id: 'bk_002', name: '뉴트럴 그립 풀 업', category: '등', equipment: '맨몸', alternativeExercises: ['bk_001'] },
  { id: 'bk_003', name: '데드리프트', category: '등', equipment: '바벨', alternativeExercises: [] },
  { id: 'ch_001', name: '딥스', category: '가슴', equipment: '맨몸', alternativeExercises: ['ch_002'] },
  { id: 'ch_002', name: '딥스 트라이셉스', category: '가슴', equipment: '머신', description: '다이나믹', alternativeExercises: ['ch_001'] },
  { id: 'bk_004', name: '랫 풀 다운', category: '등', equipment: '머신', description: '다이나믹', alternativeExercises: ['bk_015'] },
  { id: 'lg_003', name: '레그 레이즈', category: '하체', equipment: '머신', alternativeExercises: [] },
  { id: 'lg_004', name: '레그 프레스', category: '하체', equipment: '머신', alternativeExercises: ['lg_006', 'lg_005', 'lg_007'] },
  { id: 'bk_005', name: '레터럴 로우', category: '등', equipment: '머신', description: '소리넥스', alternativeExercises: ['bk_006', 'bk_009'] },
  { id: 'bk_006', name: '레터럴 로우', category: '등', equipment: '머신', alternativeExercises: ['bk_005', 'bk_009'] },
  { id: 'bk_007', name: '레터럴 로우 버티컬', category: '등', equipment: '머신', description: '소리넥스', alternativeExercises: ['bk_008'] },
  { id: 'bk_008', name: '레터럴 로우 버티컬', category: '등', equipment: '머신', alternativeExercises: ['bk_007'] },
  { id: 'bk_009', name: '로우', category: '등', equipment: '머신', description: '라이프피트니스', alternativeExercises: ['bk_005', 'bk_006'] },
  { id: 'sh_001', name: '리어 델토이드', category: '어깨', equipment: '머신', description: '라이프피트니스', alternativeExercises: ['sh_002'] },
  { id: 'sh_002', name: '리어 델토이드', category: '어깨', equipment: '머신', description: '다이나믹', alternativeExercises: ['sh_001'] },
  { id: 'sh_003', name: '밀리터리 프레스', category: '어깨', equipment: '바벨', alternativeExercises: ['sh_007'] },
  { id: 'ch_003', name: '벤치프레스', category: '가슴', equipment: '바벨', alternativeExercises: ['ch_004', 'ch_005'] },
  { id: 'ch_004', name: '벤치프레스', category: '가슴', equipment: '머신', description: '소리넥스', alternativeExercises: ['ch_003', 'ch_005'] },
  { id: 'ch_005', name: '벤치프레스', category: '가슴', equipment: '머신', description: '아메리칸', alternativeExercises: ['ch_003', 'ch_004'] },
  { id: 'sh_004', name: '벤트 오버 레터럴 레이즈', category: '어깨', equipment: '덤벨', alternativeExercises: ['sh_005', 'sh_006'] },
  { id: 'lg_005', name: '브이 스쿼트', category: '하체', equipment: '머신', description: '아메리칸', alternativeExercises: ['lg_006', 'lg_004', 'lg_007'] },
  { id: 'sh_005', name: '사이드 레터럴 레이즈', category: '어깨', equipment: '머신', alternativeExercises: ['sh_006', 'sh_004'] },
  { id: 'sh_006', name: '사이드 레터럴 레이즈 체인', category: '어깨', equipment: '머신', alternativeExercises: ['sh_005', 'sh_004'] },
  { id: 'ab_001', name: '사이드 밴드', category: '복근', equipment: '덤벨', alternativeExercises: ['ab_003'] },
  { id: 'sh_007', name: '숄더 프레스', category: '어깨', equipment: '머신', description: '아메리칸', alternativeExercises: ['sh_003'] },
  { id: 'lg_006', name: '스쿼트', category: '하체', equipment: '바벨', alternativeExercises: ['lg_004', 'lg_005', 'lg_007'] },
  { id: 'ar_001', name: '암컬', category: '팔', equipment: '머신', alternativeExercises: ['ar_003'] },
  { id: 'ab_002', name: '앱도미널', category: '복근', equipment: '머신', alternativeExercises: [] },
  { id: 'bk_010', name: '언더 그립 랫 풀 다운', category: '등', equipment: '머신', description: '다이나믹', alternativeExercises: ['bk_011'] },
  { id: 'bk_011', name: '언더핸드 친 업', category: '등', equipment: '맨몸', alternativeExercises: ['bk_010'] },
  { id: 'bk_012', name: '와이드 그립 랫 풀 다운', category: '등', equipment: '머신', description: '다이나믹', alternativeExercises: ['bk_013'] },
  { id: 'bk_013', name: '와이드 그립 풀 업', category: '등', equipment: '맨몸', alternativeExercises: ['bk_012'] },
  { id: 'ch_006', name: '인클라인 프레스', category: '가슴', equipment: '머신', description: '아메리칸', alternativeExercises: ['ch_007'] },
  { id: 'ch_007', name: '인클라인 프레스', category: '가슴', equipment: '머신', alternativeExercises: ['ch_006'] },
  { id: 'bk_014', name: '케이블 암 풀 다운', category: '등', equipment: '케이블', alternativeExercises: [] },
  { id: 'ar_002', name: '케이블 프레스 다운', category: '팔', equipment: '케이블', alternativeExercises: [] },
  { id: 'ab_003', name: '토르소 로테이션', category: '복근', equipment: '머신', description: '라이프피트니스', alternativeExercises: ['ab_001'] },
  { id: 'ch_008', name: '팩토리얼 플라이', category: '가슴', equipment: '머신', description: '라이프피트니스', alternativeExercises: ['ch_009', 'ch_010'] },
  { id: 'ch_009', name: '펙 덱 플라이', category: '가슴', equipment: '머신', description: '다이나믹', alternativeExercises: ['ch_008', 'ch_010'] },
  { id: 'ch_010', name: '펙 덱 플라이', category: '가슴', equipment: '머신', description: '엠토쳐', alternativeExercises: ['ch_008', 'ch_009'] },
  { id: 'bk_015', name: '풀 업', category: '등', equipment: '맨몸', alternativeExercises: ['bk_004'] },
  { id: 'ar_003', name: '해머 컬 머신', category: '팔', equipment: '머신', description: '다이나믹', alternativeExercises: ['ar_001'] },
  { id: 'lg_007', name: '핵스쿼트', category: '하체', equipment: '머신', description: '다이나믹', alternativeExercises: ['lg_006', 'lg_004', 'lg_005'] },
  { id: 'lg_008', name: '힙 쓰러스트', category: '하체', equipment: '머신', alternativeExercises: [] },
  { id: 'lg_009', name: '힙 어덕션', category: '하체', equipment: '머신', description: '라이프피트니스', alternativeExercises: [] },
  { id: 'lg_010', name: '힙 업덕션', category: '하체', equipment: '머신', description: '라이프피트니스', alternativeExercises: [] },
];

// 하위 호환: 기존 DEFAULT_EXERCISES 참조를 위한 alias
export const DEFAULT_EXERCISES = EXERCISES;

export const CATEGORY_LABELS: Record<ExerciseCategory, string> = {
  가슴: '가슴',
  등: '등',
  어깨: '어깨',
  팔: '팔',
  하체: '하체',
  복근: '복근',
};
